# sample data
data = [{'Title': 'SOLE PARK', 'Category': 'SCULPTURE',
         'Type': 'RELIEF', 'Medium': 'STONE', 'Frame': 'false',
         'Photo URL Link': 'UNKNOWN', 'Artist': 'UNKNOWN',
         'Street Address': 'BUSTI AVE & NIAGARA ST',
         'City': 'BUFFALO', 'Zipcode': '14213', 'State': 'NY'},
        {'Title': 'BUFFALO STREET MAP', 'Category': 'GRAPHIC ARTS',
         'Type': 'MAP', 'Medium': 'PARCHMENT', 'Frame': 'true',
         'Photo URL Link': 'UNKNOWN', 'Artist': 'SMITH BROTHERS COMPANY',
         'Street Address': '65 NIAGARA SQUARE',
         'City': 'BUFFALO', 'Zipcode': '14202', 'State': 'NY'},
        {'Title': 'WAR MEMORIAL STADIUM RENDERING', 'Category': 'GRAPHIC ARTS',
         'Type': 'DRAWING', 'Medium': 'PAPER', 'Frame': 'false',
         'Photo URL Link': 'UNKNOWN', 'Artist': 'UNKNOWN',
         'Street Address': '65 NIAGARA SQUARE',
         'City': 'BUFFALO', 'Zipcode': '14202', 'State': 'NY'},
        {'Title': 'MAYOR HIRAM BARTON', 'Category': 'PAINTINGS',
         'Type': 'PORTRAIT', 'Medium': 'OIL ON CANVAS', 'Frame': 'true',
         'Photo URL Link': 'HTTP://WWW.CI.BUFFALO.NY.US/FILES/1_2_1/PUBLIC%20ART%20WEBSITE/WEB%20PAGES/HIRAM%20BARTON.HTML', 
         'Artist': 'UNKNOWN', 'Street Address': '65 NIAGARA SQUARE',
         'City': 'BUFFALO', 'Zipcode': '14202', 'State': 'NY'},
        {'Title': 'MAYOR ELI COOK', 'Category': 'GRAPHICS ARTS',
         'Type': 'PORTRAIT', 'Medium': 'PASTEL ON PAPER', 'Frame': 'true',
         'Photo URL Link': 'HTTP://WWW.CI.BUFFALO.NY.US/FILES/1_2_1/PUBLIC%20ART%20WEBSITE/WEB%20PAGES/ELI%20COOK.HTML', 
         'Artist': 'UNKNOWN', 'Street Address': '65 NIAGARA SQUARE',
         'City': 'BUFFALO', 'Zipcode': '14202', 'State': 'NY'},
        {'Title': 'MAYOR ANTHONY MASIELLO', 'Category': 'PAINTINGS',
         'Type': 'PORTRAIT', 'Medium': 'OIL ON CANVAS', 'Frame': 'true',
         'Photo URL Link': 'UNKNOWN', 'Artist': 'NATHAN NAETZKER',
         'Street Address': '65 NIAGARA SQUARE',
         'City': 'BUFFALO', 'Zipcode': '14202', 'State': 'NY'},
        {'Title': 'MAYOR CHANDLER J WELLS', 'Category': 'PAINTINGS',
         'Type': 'PORTRAIT', 'Medium': 'OIL ON CANVAS', 'Frame': 'true',
         'Photo URL Link': 'HTTP://WWW.CI.BUFFALO.NY.US/FILES/1_2_1/PUBLIC%20ART%20WEBSITE/WEB%20PAGES/CHANDLER%20WELLS.HTML',
         'Artist': 'ALVAH BRADISH', 'Street Address': '65 NIAGARA SQUARE',
         'City': 'BUFFALO', 'Zipcode': '14202', 'State': 'NY'}]
